### ISSUE TITLE
issue while compiling roi_pooling

### ISSUE THREAD

**Issue by anujavk** [ronghanghu/cmn#9]
getting error in 3rd step of the installation
```
export CMN_ROOT=$(pwd)
cd $CMN_ROOT/util/faster_rcnn_lib/ && make
cd $CMN_ROOT/util/roi_pooling/ && ./compile_roi_pooling.sh
cd $CMN_ROOT
```
error:

```
tensorflow/core/util/cuda_kernel_helper.h(52): error: class "Eigen::GpuDevice" has no member "getNumCudaMultiProcessors"

tensorflow/core/util/cuda_kernel_helper.h(52): error: class "Eigen::GpuDevice" has no member "maxCudaThreadsPerMultiProcessor"

tensorflow/core/util/cuda_kernel_helper.h(51): error: no instance of overloaded function "std::min" matches the argument list
            argument types are: (<error-type>, const int)

tensorflow/core/util/cuda_kernel_helper.h(54): error: class "Eigen::GpuDevice" has no member "maxCudaThreadsPerBlock"

tensorflow/core/util/cuda_kernel_helper.h(54): error: no instance of overloaded function "std::min" matches the argument list
            argument types are: (int, <error-type>)

tensorflow/core/util/cuda_kernel_helper.h(57): error: class "Eigen::GpuDevice" has no member "getNumCudaMultiProcessors"

10 errors detected in the compilation of "/tmp/tmpxft_00002353_00000000-7_roi_pooling_op_gpu.cu.cpp1.ii".
g++-4.8: error: roi_pooling_op_gpu.cu.o: No such file or directory
```
@ronghanghu

**Comment by yuhorun** [comment]
> getting error in 3rd step of the installation
> 
> ```
> export CMN_ROOT=$(pwd)
> cd $CMN_ROOT/util/faster_rcnn_lib/ && make
> cd $CMN_ROOT/util/roi_pooling/ && ./compile_roi_pooling.sh
> cd $CMN_ROOT
> ```
> 
> error:
> 
> ```
> tensorflow/core/util/cuda_kernel_helper.h(52): error: class "Eigen::GpuDevice" has no member "getNumCudaMultiProcessors"
> 
> tensorflow/core/util/cuda_kernel_helper.h(52): error: class "Eigen::GpuDevice" has no member "maxCudaThreadsPerMultiProcessor"
> 
> tensorflow/core/util/cuda_kernel_helper.h(51): error: no instance of overloaded function "std::min" matches the argument list
>             argument types are: (<error-type>, const int)
> 
> tensorflow/core/util/cuda_kernel_helper.h(54): error: class "Eigen::GpuDevice" has no member "maxCudaThreadsPerBlock"
> 
> tensorflow/core/util/cuda_kernel_helper.h(54): error: no instance of overloaded function "std::min" matches the argument list
>             argument types are: (int, <error-type>)
> 
> tensorflow/core/util/cuda_kernel_helper.h(57): error: class "Eigen::GpuDevice" has no member "getNumCudaMultiProcessors"
> 
> 10 errors detected in the compilation of "/tmp/tmpxft_00002353_00000000-7_roi_pooling_op_gpu.cu.cpp1.ii".
> g++-4.8: error: roi_pooling_op_gpu.cu.o: No such file or directory
> ```
> 
> @ronghanghu

have you solved thequestion？
